M48
; DRILL file {KiCad (5.99.0-10483-ga6ad7a4a70)} date Mon May 17 14:47:57 2021
; FORMAT={2:4/ absolute / inch / suppress leading zeros}
; #@! TF.CreationDate,2021-05-17T14:47:57+02:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(5.99.0-10483-ga6ad7a4a70)
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH,TZ
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0354
%
G90
G05
T1
X37764Y-44510
X39496Y-44510
T0
M30
